swagger: '2.0'
info:
  description: >-
    Writing a (gg) service from scratch.
  title: Tutorial Service
  version: 0.1.0
basePath: "/"
paths: 
  '/lock/resource/{id}':
    x-swagger-router-controller: lockingController
    get:
      tags:
      - "getIsLockedByResourceId"
      description: Queries the state of a lock on a resource by id.
      operationId: getIsLockedByResourceId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: "path"
        name: "id"
        type: string
        required: true
        description: The id of the resource to query.
      responses:
        200:
          description: OK
          schema:
            type: boolean

